import type { OxlintConfig } from 'oxlint'
import { globExclude } from '~/config/oxc-glob-exclude'

export const oxlintConfig: OxlintConfig = {
  categories: {
    correctness: 'error',
    perf: 'error',
    restriction: 'error',
    style: 'error',
    suspicious: 'error',
  },
  ignorePatterns: globExclude,
  options: {
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      files: ['*.config.ts', '*.config.mts', '*.config.mjs', '*.config.js', '*.config.cjs'],
      rules: {
        'eslint/sort-keys': 'warn',
      },
    },
  ],
  plugins: [
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
    'import',
    'jsdoc',
    'jsx-a11y',
    'node',
    'promise',
    'vitest',
  ],
  rules: {
    'eslint/capitalized-comments': 'off',
    'eslint/func-style': 'off',
    'eslint/id-length': 'off',
    'eslint/init-declarations': 'off',
    'eslint/max-statements': 'off',
    'eslint/no-await-in-loop': 'off',
    'eslint/no-console': ['warn', { allow: ['warn', 'error'] }],
    'eslint/no-continue': 'off',
    'eslint/no-duplicate-imports': 'off',
    'eslint/no-magic-numbers': 'off',
    'eslint/no-shadow': 'off',
    'eslint/no-ternary': 'off',
    'eslint/no-unused-expressions': [
      'warn',
      { allowShortCircuit: true, allowTaggedTemplates: true, allowTernary: true },
    ],
    'eslint/no-use-before-define': ['warn', { classes: false, functions: false, variables: true }],
    'eslint/prefer-destructuring': 'off',
    'eslint/sort-imports': 'off',
    'eslint/sort-keys': 'off',
    'import/exports-last': 'off',
    'import/group-exports': 'off',
    'import/no-default-export': 'off',
    'import/no-named-export': 'off',
    'import/no-nodejs-modules': 'off',
    'import/no-relative-parent-imports': 'off',
    'import/no-unassigned-import': 'off',
    'import/prefer-default-export': 'off',
    'import/unambiguous': 'off',
    'jest/prefer-strict-equal': 'off',
    'jest/require-hook': 'off',
    'jest/valid-title': 'off',
    'oxc/no-async-await': 'off',
    'oxc/no-async-endpoint-handlers': 'off',
    'oxc/no-optional-chaining': 'off',
    'oxc/no-rest-spread-properties': 'off',
    'promise/prefer-await-to-then': 'off',
    'typescript/ban-types': 'error',
    'typescript/consistent-return': 'off',
    'typescript/consistent-type-imports': [
      'warn',
      {
        disallowTypeAnnotations: false,
        fixStyle: 'separate-type-imports',
        prefer: 'type-imports',
      },
    ],
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-member-accessibility': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/no-empty-interface': 'off',
    'typescript/no-empty-object-type': 'off',
    'typescript/no-explicit-any': 'off',
    'typescript/no-floating-promises': 'off',
    'typescript/no-inferrable-types': 'off',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/promise-function-async': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-null': 'off',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/relative-url-style': 'off',
    'vitest/no-importing-vitest-globals': 'off',
    'vitest/require-test-timeout': 'off',
  },
}
