import type { OxlintConfig } from 'oxlint'

export const oxlintConfig: OxlintConfig = {
  categories: {
    correctness: 'error',
    perf: 'error',
    restriction: 'error',
    style: 'error',
    suspicious: 'error',
  },
  options: {
    typeAware: true,
    typeCheck: true,
  },
  plugins: [
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
    'import',
    'jsdoc',
    'jsx-a11y',
    'node',
    'promise',
    'vitest',
  ],
  rules: {
    'eslint/func-style': 'off',
    'eslint/id-length': 'off',
    'eslint/max-statements': 'off',
    'eslint/no-await-in-loop': 'off',
    'eslint/no-continue': 'off',
    'eslint/no-duplicate-imports': 'off',
    'eslint/no-magic-numbers': 'off',
    'eslint/no-shadow': 'off',
    'eslint/no-ternary': 'off',
    'eslint/no-unused-expressions': [
      'warn',
      { allowShortCircuit: true, allowTaggedTemplates: true, allowTernary: true },
    ],
    'eslint/no-use-before-define': ['warn', { classes: false, functions: false, variables: true }],
    'eslint/prefer-destructuring': 'off',
    'eslint/sort-imports': 'off',
    'eslint/sort-keys': 'warn',
    'import/exports-last': 'off',
    'import/group-exports': 'off',
    'import/no-default-export': 'off',
    'import/no-named-export': 'off',
    'import/no-nodejs-modules': 'off',
    'import/prefer-default-export': 'off',
    'import/unambiguous': 'off',
    'jest/prefer-strict-equal': 'off',
    'jest/valid-title': 'off',
    'oxc/no-async-await': 'off',
    'oxc/no-async-endpoint-handlers': 'off',
    'oxc/no-optional-chaining': 'off',
    'oxc/no-rest-spread-properties': 'off',
    'promise/prefer-await-to-then': 'off',
    'typescript/ban-types': 'error',
    'typescript/consistent-return': 'off',
    'typescript/consistent-type-imports': [
      'warn',
      {
        disallowTypeAnnotations: false,
        fixStyle: 'separate-type-imports',
        prefer: 'type-imports',
      },
    ],
    'typescript/explicit-function-return-type': [
      'warn',
      { allowExpressions: true, allowHigherOrderFunctions: true, allowIIFEs: true },
    ],
    'typescript/explicit-member-accessibility': 'off',
    'typescript/no-floating-promises': 'off',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/promise-function-async': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-null': 'off',
    'unicorn/prefer-node-protocol': 'error',
    'vitest/no-importing-vitest-globals': 'off',
    'vitest/require-test-timeout': 'off',
  },
}
