import type { OxlintConfig } from 'oxlint'
import { globExclude } from '~/config/oxc-glob-exclude'

export const oxlintReactConfig: OxlintConfig = {
  plugins: ['react', 'react-perf', 'jsx-a11y'],
  rules: {
    'jsx-a11y/no-autofocus': 'off',
    'react-perf/jsx-no-jsx-as-prop': 'off',
    'react-perf/jsx-no-new-array-as-prop': 'off',
    'react-perf/jsx-no-new-object-as-prop': 'off',
    'react/forbid-component-props': 'off',
    'react/jsx-boolean-value': 'off',
    'react/jsx-filename-extension': 'off',
    'react/jsx-max-depth': 'off',
    'react/jsx-props-no-spreading': 'off',

    'react/no-multi-comp': 'off',
    'react/no-unknown-property': 'off',
    'react/only-export-components': 'off',

    'react/react-in-jsx-scope': 'off',
  },
}

export const oxlintConfig: OxlintConfig = {
  categories: {
    correctness: 'error',
    perf: 'error',
    restriction: 'error',
    style: 'error',
    suspicious: 'error',
  },
  ignorePatterns: globExclude,
  options: {
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      files: ['*.config.ts', '*.config.mts', '*.config.mjs', '*.config.js', '*.config.cjs'],
      rules: {
        'eslint/sort-keys': 'warn',
      },
    },
    {
      files: ['**/*.{test,spec}.{ts,tsx,js,jsx}', '**/__tests__/**/*.{ts,tsx,js,jsx}'],
      plugins: ['jest', 'vitest'],
      rules: {
        'jest/prefer-expect-assertions': 'off',
        'jest/prefer-strict-equal': 'off',
        'jest/require-hook': 'off',
        'jest/valid-title': 'off',
        'vitest/no-importing-vitest-globals': 'off',
        'vitest/prefer-expect-assertions': 'off',
        'vitest/prefer-strict-boolean-matchers': 'off',
        'vitest/prefer-to-be-falsy': 'off',
        'vitest/require-test-timeout': 'off',
      },
    },
    {
      files: ['**/routeTree.gen.ts'],
      rules: {
        'unicorn/filename-case': 'off',
        'unicorn/no-abusive-eslint-disable': 'off',
      },
    },
  ],
  plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'import', 'jsdoc', 'node', 'promise'],
  rules: {
    'eslint/capitalized-comments': 'off',
    'eslint/func-style': 'off',
    'eslint/id-length': 'off',
    'eslint/init-declarations': 'off',
    'eslint/max-statements': 'off',
    'eslint/no-await-in-loop': 'off',
    'eslint/no-console': [
      'warn',
      {
        allow: ['warn', 'error'],
      },
    ],
    'eslint/no-continue': 'off',
    'eslint/no-duplicate-imports': 'off',
    'eslint/no-empty-function': 'warn',
    'eslint/no-magic-numbers': 'off',
    'eslint/no-shadow': 'off',
    'eslint/no-ternary': 'off',
    'eslint/no-undefined': 'off',
    'eslint/no-unused-expressions': [
      'warn',
      {
        allowShortCircuit: true,
        allowTaggedTemplates: true,
        allowTernary: true,
      },
    ],
    'eslint/no-unused-vars': 'warn',
    'eslint/no-use-before-define': [
      'warn',
      {
        classes: false,
        functions: false,
        variables: true,
      },
    ],
    'eslint/prefer-destructuring': 'off',
    'eslint/sort-imports': 'off',
    'eslint/sort-keys': 'off',
    'import/exports-last': 'off',
    'import/group-exports': 'off',
    'import/no-default-export': 'off',
    'import/no-named-export': 'off',
    'import/no-nodejs-modules': 'off',
    'import/no-relative-parent-imports': 'off',
    'import/no-unassigned-import': 'off',
    'import/prefer-default-export': 'off',
    'import/unambiguous': 'off',
    'oxc/no-async-await': 'off',
    'oxc/no-async-endpoint-handlers': 'off',
    'oxc/no-optional-chaining': 'off',
    'oxc/no-rest-spread-properties': 'off',
    'promise/always-return': 'off',
    'promise/catch-or-return': 'off',
    'promise/prefer-await-to-then': 'off',
    'typescript/ban-types': 'error',
    'typescript/consistent-return': 'off',
    'typescript/consistent-type-imports': [
      'warn',
      {
        disallowTypeAnnotations: false,
        fixStyle: 'separate-type-imports',
        prefer: 'type-imports',
      },
    ],
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-member-accessibility': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/no-empty-interface': 'off',
    'typescript/no-empty-object-type': 'off',
    'typescript/no-explicit-any': 'off',
    'typescript/no-floating-promises': 'off',
    'typescript/no-inferrable-types': 'off',
    'typescript/no-non-null-assertion': 'off',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/promise-function-async': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-null': 'off',
    'unicorn/prefer-global-this': 'off',
    'unicorn/prefer-module': 'off',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/relative-url-style': 'off',
  },
}
